import FirstComponent from "@/components/first";
import SecondComponent from "@/components/second/second";
import Head from "next/head";

export default function Home() {
  const messageValue = "Hello World!";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>My message is : {messageValue}</h1>
      <FirstComponent message={messageValue} />
      <SecondComponent />
    </>
  );
}
